feature: exports route definitions
yesmeck/remix-routes pull request #40
Opened 2023-02-07 02:38 UTC by yesmeck

2023-02-07 12:51 UTC, moishinetzer requested changes
![image](https://user-images.githubusercontent.com/11411486/217249388-0e7fcc4a-8c5d-4411-92d3-478d4461d7d2.png)

I'm on a windows machine using node 18, it seems the routes arent being generated correctly, they are using backslashes for some reason.

Other than that, this looks great!

2023-02-07 12:57 UTC, moishinetzer commented
![image](https://user-images.githubusercontent.com/11411486/217250736-c6494368-45bd-42a8-848d-11ae98d6afd9.png)
![image](https://user-images.githubusercontent.com/11411486/217250749-4e215efc-6658-4c25-87cc-6ab1ad276566.png)

Also, note that the query requires square brackets. I assume one of the types are not being spread properly.

I'm using the redirect implementation that you recommended in the original issue.

2023-02-07 13:50 UTC, yesmeck commented
The query type is just a alias of your route's SearchParams type.

2023-02-07 13:51 UTC, moishinetzer commented
> The query type is just a alias of your route's SearchParams type.

correct, but it needs to be wrapped in square brackets, I'm assuming the wanted functionality is as shown in the first image

2023-02-12 10:55 UTC, yesmeck commented
> > The query type is just a alias of your route's SearchParams type.
> 
> correct, but it needs to be wrapped in square brackets, I'm assuming the wanted functionality is as shown in the first image.
> 
> My code looks like
> 
> ```tsx
> export type SearchParams = {
>   ascending: "true" | "false"
> }
> ```

It should be corrected now.

2023-02-12 10:55 UTC, merged

2023-02-12 10:56 UTC, yesmeck commented
Added a windows runner for CI, the path issue should be fixed as well.

2023-02-12 11:00 UTC, yesmeck commented
Released in 1.4.0

2023-02-12 13:10 UTC, moishinetzer commented
Thanks so much for all your help! I really appreciate it ❤️